import { assetPath } from "@/lib/assets";

import type { RenewalSeed } from "./types";

// Static fixtures until a real data source is wired up.

// Cancel-by dates, contract values, owners and usage are reconciled against
// each vendor's full record in @/features/renewal-detail/mock-data ("today"
// is Sep 26 there). Risk, timing and ranking are computed in ./assessment.
export const renewals: RenewalSeed[] = [
  {
    vendor: "Salesforce",
    subtitle: "Project Management",
    logo: assetPath("vendor-salesforce.png"),
    cancelBy: "Sept 20",
    daysToCancelBy: -6,
    contractValue: 180_000,
    contractType: "Auto-renew",
    owner: null,
    team: null,
    vacancy: "departed",
    formerOwner: "Elena Chen",
    usage: "64%",
    status: "Assign owner",
    statusTone: "orange",
    action: "Review",
  },
  {
    vendor: "Atlassian",
    subtitle: "Coding Agent",
    logo: assetPath("vendor-atlassian.png"),
    cancelBy: "Nov 20",
    daysToCancelBy: 55,
    contractValue: 96_000,
    contractType: "Auto-renew",
    owner: "Rohan Mehta",
    team: "Engineering",
    usage: "85%",
    status: "In review",
    statusTone: "blue",
    action: "Review",
  },
  {
    vendor: "Zapier",
    subtitle: "CRM",
    logo: assetPath("vendor-zapier.png"),
    cancelBy: "Sept 28",
    daysToCancelBy: 2,
    contractValue: 96_000,
    contractType: "Manual",
    owner: null,
    team: null,
    vacancy: "unassigned",
    formerOwner: "Rohan Mehta",
    usage: "78%",
    status: "On track",
    statusTone: "green",
    action: "Assign",
  },
  {
    vendor: "Notion",
    subtitle: "Coding Agent",
    logo: assetPath("vendor-notion.png"),
    cancelBy: "Nov 6",
    daysToCancelBy: 41,
    contractValue: 96_000,
    contractType: "Month-to-month",
    owner: "Jasmine Patel",
    team: "Finance",
    usage: "88%",
    status: "Monitor",
    statusTone: "grey",
    action: "View",
  },
  {
    vendor: "Vercel",
    subtitle: "Coding Agent",
    logo: assetPath("vendor-vercel.png"),
    cancelBy: "Nov 6",
    daysToCancelBy: 41,
    contractValue: 96_000,
    contractType: "Month-to-month",
    owner: "Marcus Webb",
    team: "Engineering",
    usage: "91%",
    status: "Needs decision",
    statusTone: "red",
    action: "View",
  },
];
